- name: bug
  description: Something isn't working
  color: d42a34

- name: dependencies
  description: Related with project dependencies
  color: ffc0cb

- name: documentation
  description: Improvements or additions to documentation
  color: 0677ba

- name: enhancement
  description: New features or code improvements
  color: FFD827

- name: good first issue
  description: Easy to solve for newcomers
  color: 62ca50

- name: maintenance
  description: Package and maintenance related
  color: f78c37

- name: release
  description: Anything related to an incoming release
  color: ffffff

- name: testing
  description: Anything related to tests
  color: BFE4D6

- name: security
  description: Anything related to security advisories
  color: FF0000

- name: p1
  description: Priority 1 - High priority issues
  color: 4300FF

- name: p2
  description: Priority 2 - Medium priority issues
  color: 008000

- name: p3
  description: Priority 3 - Low priority issues
  color: FFA500

- name: needs-service-implementation
  description: Issue requires service implementation
  color: c27ba0
