ci:
  autofix_commit_msg: 'chore: auto fixes from pre-commit hooks'

exclude: "tests/integration/files|uv\\.lock"
repos:

  - repo: https://github.com/google/yamlfmt
    rev: 21ca5323a9c87ee37a434e0ca908efc0a89daa07 # frozen: v0.21.0
    hooks:
      - id: yamlfmt
        args:
          - "-formatter"
          - "max_line_length=120,retain_line_breaks=true,retain_line_breaks_single=true"
          - "-exclude"
          - ".codacy.yml"

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: 0c8c15d8fe996493035be407c5cf4a288cf6bf8e # frozen: v2.25.1
    hooks:
      - id: pyproject-fmt
        args: [--keep-full-version]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: c59bba8fb259db0fec2bbb77ad8ba51ea7341b56 # frozen: v0.15.20
    hooks:
      - id: ruff-check
      - id: ruff-format

  - repo: https://github.com/codespell-project/codespell
    rev: 2ccb47ff45ad361a21071a7eedda4c37e6ae8c5a # frozen: v2.4.2
    hooks:
      - id: codespell
        args: ["--ignore-words", "doc/styles/config/vocabularies/ANSYS/accept.txt", "-w"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-yaml
      - id: trailing-whitespace

  - repo: https://github.com/ansys/pre-commit-hooks
    rev: 55c5b6a5439abd847613579c6924da750e8b78b2 # frozen: v0.8.0
    hooks:
      - id: add-license-headers
        args:
          - --start_year=2023

  # this validates our github workflow files
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 5030dca3047414c338091455ac41803200ec1f0f # frozen: 0.37.3
    hooks:
      - id: check-github-workflows

  # this validates our pre-commit.ci configuration
  - repo: https://github.com/pre-commit-ci/pre-commit-ci-config
    rev: 500543de231a91e6157db630075d70320709b834 # frozen: v1.6.1
    hooks:
      - id: check-pre-commit-ci-config
