# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ansys/api/geometry/v0/designs.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode("latin1"))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="ansys/api/geometry/v0/designs.proto",
    package="ansys.api.geometry.v0",
    syntax="proto3",
    serialized_options=_b("\252\002\025Ansys.Api.Geometry.V0"),
    serialized_pb=_b(
        '\n#ansys/api/geometry/v0/designs.proto\x12\x15\x61nsys.api.geometry.v0"!\n\x10NewDesignRequest\x12\r\n\x05label\x18\x01 \x01(\t"#\n\x06\x44\x65sign\x12\r\n\x05label\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t2X\n\x07\x44\x65signs\x12M\n\x03New\x12\'.ansys.api.geometry.v0.NewDesignRequest\x1a\x1d.ansys.api.geometry.v0.DesignB\x18\xaa\x02\x15\x41nsys.Api.Geometry.V0b\x06proto3'
    ),
)


_NEWDESIGNREQUEST = _descriptor.Descriptor(
    name="NewDesignRequest",
    full_name="ansys.api.geometry.v0.NewDesignRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="label",
            full_name="ansys.api.geometry.v0.NewDesignRequest.label",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=62,
    serialized_end=95,
)


_DESIGN = _descriptor.Descriptor(
    name="Design",
    full_name="ansys.api.geometry.v0.Design",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="label",
            full_name="ansys.api.geometry.v0.Design.label",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="id",
            full_name="ansys.api.geometry.v0.Design.id",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=97,
    serialized_end=132,
)

DESCRIPTOR.message_types_by_name["NewDesignRequest"] = _NEWDESIGNREQUEST
DESCRIPTOR.message_types_by_name["Design"] = _DESIGN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NewDesignRequest = _reflection.GeneratedProtocolMessageType(
    "NewDesignRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _NEWDESIGNREQUEST,
        "__module__": "ansys.api.geometry.v0.designs_pb2"
        # @@protoc_insertion_point(class_scope:ansys.api.geometry.v0.NewDesignRequest)
    },
)
_sym_db.RegisterMessage(NewDesignRequest)

Design = _reflection.GeneratedProtocolMessageType(
    "Design",
    (_message.Message,),
    {
        "DESCRIPTOR": _DESIGN,
        "__module__": "ansys.api.geometry.v0.designs_pb2"
        # @@protoc_insertion_point(class_scope:ansys.api.geometry.v0.Design)
    },
)
_sym_db.RegisterMessage(Design)


DESCRIPTOR._options = None

_DESIGNS = _descriptor.ServiceDescriptor(
    name="Designs",
    full_name="ansys.api.geometry.v0.Designs",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=134,
    serialized_end=222,
    methods=[
        _descriptor.MethodDescriptor(
            name="New",
            full_name="ansys.api.geometry.v0.Designs.New",
            index=0,
            containing_service=None,
            input_type=_NEWDESIGNREQUEST,
            output_type=_DESIGN,
            serialized_options=None,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_DESIGNS)

DESCRIPTOR.services_by_name["Designs"] = _DESIGNS

# @@protoc_insertion_point(module_scope)
