# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from ansys.api.geometry import board_pb2 as ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2


class BoardStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
        """Constructor.

        Args:
          channel: A grpc.Channel.
        """
        self.AddMaterialToDocument = channel.unary_unary(
            "/ansys.api.geometry.v0.Board/AddMaterialToDocument",
            request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.AddMaterialToDocumentRequest.SerializeToString,
            response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.AddMaterialToDocumentResponse.FromString,
        )
        self.GetMaterialNames = channel.unary_unary(
            "/ansys.api.geometry.v0.Board/GetMaterialNames",
            request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.Empty.SerializeToString,
            response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.GetMaterialNamesResponse.FromString,
        )
        self.GetAllComponents = channel.unary_unary(
            "/ansys.api.geometry.v0.Board/GetAllComponents",
            request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.Empty.SerializeToString,
            response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.GetAllComponentsResponse.FromString,
        )
        self.GetComponentBodies = channel.unary_unary(
            "/ansys.api.geometry.v0.Board/GetComponentBodies",
            request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.GetComponentBodiesRequest.SerializeToString,
            response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.GetComponentBodiesResponse.FromString,
        )
        self.GetComponentName = channel.unary_unary(
            "/ansys.api.geometry.v0.Board/GetComponentName",
            request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.GetComponentNameRequest.SerializeToString,
            response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.GetComponentNameResponse.FromString,
        )
        self.CreateNamedSelection = channel.unary_unary(
            "/ansys.api.geometry.v0.Board/CreateNamedSelection",
            request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.CreateNamedSelectionRequest.SerializeToString,
            response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.Empty.FromString,
        )
        self.SetBodyMaterialByName = channel.unary_unary(
            "/ansys.api.geometry.v0.Board/SetBodyMaterialByName",
            request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.SetBodyMaterialByNameRequest.SerializeToString,
            response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.Empty.FromString,
        )
        self.TranslateBody = channel.unary_unary(
            "/ansys.api.geometry.v0.Board/TranslateBody",
            request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.TranslateBodyRequest.SerializeToString,
            response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.Empty.FromString,
        )
        self.GetRootComponent = channel.unary_unary(
            "/ansys.api.geometry.v0.Board/GetRootComponent",
            request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.Empty.SerializeToString,
            response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.GetRootComponentResponse.FromString,
        )
        self.GetBodyFaces = channel.unary_unary(
            "/ansys.api.geometry.v0.Board/GetBodyFaces",
            request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.GetBodyFacesRequest.SerializeToString,
            response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.GetBodyFacesResponse.FromString,
        )
        self.GetFaceEdges = channel.unary_unary(
            "/ansys.api.geometry.v0.Board/GetFaceEdges",
            request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.GetFaceEdgesRequest.SerializeToString,
            response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.GetFaceEdgesResponse.FromString,
        )
        self.GetFaceArea = channel.unary_unary(
            "/ansys.api.geometry.v0.Board/GetFaceArea",
            request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.GetFaceAreaRequest.SerializeToString,
            response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.GetFaceAreaResponse.FromString,
        )
        self.GetEdgeFaces = channel.unary_unary(
            "/ansys.api.geometry.v0.Board/GetEdgeFaces",
            request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.GetEdgeFacesRequest.SerializeToString,
            response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.GetEdgeFacesResponse.FromString,
        )
        self.GetEdgeLength = channel.unary_unary(
            "/ansys.api.geometry.v0.Board/GetEdgeLength",
            request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.GetEdgeLengthRequest.SerializeToString,
            response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.GetEdgeLengthResponse.FromString,
        )
        self.GetFaceLoops = channel.unary_unary(
            "/ansys.api.geometry.v0.Board/GetFaceLoops",
            request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.GetFaceLoopsRequest.SerializeToString,
            response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.GetFaceLoopsResponse.FromString,
        )
        self.GetFaceNormal = channel.unary_unary(
            "/ansys.api.geometry.v0.Board/GetFaceNormal",
            request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.GetFaceNormalRequest.SerializeToString,
            response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.GetFaceNormalResponse.FromString,
        )
        self.EvaluateFace = channel.unary_unary(
            "/ansys.api.geometry.v0.Board/EvaluateFace",
            request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.EvaluateFaceRequest.SerializeToString,
            response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.EvaluateFaceResponse.FromString,
        )
        self.FaceHasInnerLoop = channel.unary_unary(
            "/ansys.api.geometry.v0.Board/FaceHasInnerLoop",
            request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.FaceHasInnerLoopRequest.SerializeToString,
            response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.FaceHasInnerLoopResponse.FromString,
        )
        self.CreateSurfaceDesignBodyFromFace = channel.unary_unary(
            "/ansys.api.geometry.v0.Board/CreateSurfaceDesignBodyFromFace",
            request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.CreateSurfaceDesignBodyFromFaceRequest.SerializeToString,
            response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.CreateSurfaceDesignBodyFromFaceResponse.FromString,
        )
        self.CreateExtrudedDesignBodyFromFaceProfile = channel.unary_unary(
            "/ansys.api.geometry.v0.Board/CreateExtrudedDesignBodyFromFaceProfile",
            request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.CreateExtrudedDesignBodyFromFaceProfileRequest.SerializeToString,
            response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.CreateExtrudedDesignBodyFromFaceProfileResponse.FromString,
        )
        self.DeleteDesignBody = channel.unary_unary(
            "/ansys.api.geometry.v0.Board/DeleteDesignBody",
            request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.DeleteDesignBodyRequest.SerializeToString,
            response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.Empty.FromString,
        )
        self.DeleteNamedSelectionByName = channel.unary_unary(
            "/ansys.api.geometry.v0.Board/DeleteNamedSelectionByName",
            request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.DeleteNamedSelectionByNameRequest.SerializeToString,
            response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.Empty.FromString,
        )
        self.DeleteComponent = channel.unary_unary(
            "/ansys.api.geometry.v0.Board/DeleteComponent",
            request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.DeleteComponentRequest.SerializeToString,
            response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.Empty.FromString,
        )
        self.ProjectCurves = channel.unary_unary(
            "/ansys.api.geometry.v0.Board/ProjectCurves",
            request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.ProjectCurvesRequest.SerializeToString,
            response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.ProjectCurvesResponse.FromString,
        )
        self.ImprintCurves = channel.unary_unary(
            "/ansys.api.geometry.v0.Board/ImprintCurves",
            request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.ImprintCurvesRequest.SerializeToString,
            response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.ImprintCurvesResponse.FromString,
        )
        self.CreateExtrudedDesignBody = channel.unary_unary(
            "/ansys.api.geometry.v0.Board/CreateExtrudedDesignBody",
            request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.CreateExtrudedDesignBodyRequest.SerializeToString,
            response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.CreateExtrudedDesignBodyResponse.FromString,
        )
        self.SetComponentSharedTopology = channel.unary_unary(
            "/ansys.api.geometry.v0.Board/SetComponentSharedTopology",
            request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.SetComponentSharedTopologyRequest.SerializeToString,
            response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.Empty.FromString,
        )
        self.CreateCoordinateSystem = channel.unary_unary(
            "/ansys.api.geometry.v0.Board/CreateCoordinateSystem",
            request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.CreateCoordinateSystemRequest.SerializeToString,
            response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.CreateCoordinateSystemResponse.FromString,
        )
        self.PowerSelectFacesByAreaRange = channel.unary_unary(
            "/ansys.api.geometry.v0.Board/PowerSelectFacesByAreaRange",
            request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.PowerSelectFacesByAreaRangeRequest.SerializeToString,
            response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.PowerSelectFacesByAreaRangeResponse.FromString,
        )
        self.CreatePlanarDesignBody = channel.unary_unary(
            "/ansys.api.geometry.v0.Board/CreatePlanarDesignBody",
            request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.CreatePlanarDesignBodyRequest.SerializeToString,
            response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.CreatePlanarDesignBodyResponse.FromString,
        )
        self.New = channel.unary_unary(
            "/ansys.api.geometry.v0.Board/New",
            request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.Empty.SerializeToString,
            response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.NewDocumentResponse.FromString,
        )
        self.SaveAs = channel.unary_unary(
            "/ansys.api.geometry.v0.Board/SaveAs",
            request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.SaveAsDocumentRequest.SerializeToString,
            response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.SaveAsDocumentResponse.FromString,
        )
        self.CreateComponent = channel.unary_unary(
            "/ansys.api.geometry.v0.Board/CreateComponent",
            request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.CreateComponentRequest.SerializeToString,
            response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.CreateComponentResponse.FromString,
        )
        self.CreateBeamCircularProfile = channel.unary_unary(
            "/ansys.api.geometry.v0.Board/CreateBeamCircularProfile",
            request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.CreateBeamCircularProfileRequest.SerializeToString,
            response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.CreateBeamCircularProfileResponse.FromString,
        )
        self.CreateBeamBodyLine = channel.unary_unary(
            "/ansys.api.geometry.v0.Board/CreateBeamBodyLine",
            request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.CreateBeamBodyLineRequest.SerializeToString,
            response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.CreateBeamBodyLineResponse.FromString,
        )


class BoardServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def AddMaterialToDocument(self, request, context):
        """Adds a material to the current document"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetMaterialNames(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetAllComponents(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetComponentBodies(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetComponentName(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreateNamedSelection(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SetBodyMaterialByName(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def TranslateBody(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetRootComponent(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetBodyFaces(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetFaceEdges(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetFaceArea(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetEdgeFaces(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetEdgeLength(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetFaceLoops(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetFaceNormal(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def EvaluateFace(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def FaceHasInnerLoop(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreateSurfaceDesignBodyFromFace(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreateExtrudedDesignBodyFromFaceProfile(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteDesignBody(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteNamedSelectionByName(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteComponent(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ProjectCurves(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ImprintCurves(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreateExtrudedDesignBody(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SetComponentSharedTopology(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreateCoordinateSystem(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def PowerSelectFacesByAreaRange(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreatePlanarDesignBody(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def New(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SaveAs(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreateComponent(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreateBeamCircularProfile(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreateBeamBodyLine(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_BoardServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "AddMaterialToDocument": grpc.unary_unary_rpc_method_handler(
            servicer.AddMaterialToDocument,
            request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.AddMaterialToDocumentRequest.FromString,
            response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.AddMaterialToDocumentResponse.SerializeToString,
        ),
        "GetMaterialNames": grpc.unary_unary_rpc_method_handler(
            servicer.GetMaterialNames,
            request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.Empty.FromString,
            response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.GetMaterialNamesResponse.SerializeToString,
        ),
        "GetAllComponents": grpc.unary_unary_rpc_method_handler(
            servicer.GetAllComponents,
            request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.Empty.FromString,
            response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.GetAllComponentsResponse.SerializeToString,
        ),
        "GetComponentBodies": grpc.unary_unary_rpc_method_handler(
            servicer.GetComponentBodies,
            request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.GetComponentBodiesRequest.FromString,
            response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.GetComponentBodiesResponse.SerializeToString,
        ),
        "GetComponentName": grpc.unary_unary_rpc_method_handler(
            servicer.GetComponentName,
            request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.GetComponentNameRequest.FromString,
            response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.GetComponentNameResponse.SerializeToString,
        ),
        "CreateNamedSelection": grpc.unary_unary_rpc_method_handler(
            servicer.CreateNamedSelection,
            request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.CreateNamedSelectionRequest.FromString,
            response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.Empty.SerializeToString,
        ),
        "SetBodyMaterialByName": grpc.unary_unary_rpc_method_handler(
            servicer.SetBodyMaterialByName,
            request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.SetBodyMaterialByNameRequest.FromString,
            response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.Empty.SerializeToString,
        ),
        "TranslateBody": grpc.unary_unary_rpc_method_handler(
            servicer.TranslateBody,
            request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.TranslateBodyRequest.FromString,
            response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.Empty.SerializeToString,
        ),
        "GetRootComponent": grpc.unary_unary_rpc_method_handler(
            servicer.GetRootComponent,
            request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.Empty.FromString,
            response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.GetRootComponentResponse.SerializeToString,
        ),
        "GetBodyFaces": grpc.unary_unary_rpc_method_handler(
            servicer.GetBodyFaces,
            request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.GetBodyFacesRequest.FromString,
            response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.GetBodyFacesResponse.SerializeToString,
        ),
        "GetFaceEdges": grpc.unary_unary_rpc_method_handler(
            servicer.GetFaceEdges,
            request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.GetFaceEdgesRequest.FromString,
            response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.GetFaceEdgesResponse.SerializeToString,
        ),
        "GetFaceArea": grpc.unary_unary_rpc_method_handler(
            servicer.GetFaceArea,
            request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.GetFaceAreaRequest.FromString,
            response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.GetFaceAreaResponse.SerializeToString,
        ),
        "GetEdgeFaces": grpc.unary_unary_rpc_method_handler(
            servicer.GetEdgeFaces,
            request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.GetEdgeFacesRequest.FromString,
            response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.GetEdgeFacesResponse.SerializeToString,
        ),
        "GetEdgeLength": grpc.unary_unary_rpc_method_handler(
            servicer.GetEdgeLength,
            request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.GetEdgeLengthRequest.FromString,
            response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.GetEdgeLengthResponse.SerializeToString,
        ),
        "GetFaceLoops": grpc.unary_unary_rpc_method_handler(
            servicer.GetFaceLoops,
            request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.GetFaceLoopsRequest.FromString,
            response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.GetFaceLoopsResponse.SerializeToString,
        ),
        "GetFaceNormal": grpc.unary_unary_rpc_method_handler(
            servicer.GetFaceNormal,
            request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.GetFaceNormalRequest.FromString,
            response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.GetFaceNormalResponse.SerializeToString,
        ),
        "EvaluateFace": grpc.unary_unary_rpc_method_handler(
            servicer.EvaluateFace,
            request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.EvaluateFaceRequest.FromString,
            response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.EvaluateFaceResponse.SerializeToString,
        ),
        "FaceHasInnerLoop": grpc.unary_unary_rpc_method_handler(
            servicer.FaceHasInnerLoop,
            request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.FaceHasInnerLoopRequest.FromString,
            response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.FaceHasInnerLoopResponse.SerializeToString,
        ),
        "CreateSurfaceDesignBodyFromFace": grpc.unary_unary_rpc_method_handler(
            servicer.CreateSurfaceDesignBodyFromFace,
            request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.CreateSurfaceDesignBodyFromFaceRequest.FromString,
            response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.CreateSurfaceDesignBodyFromFaceResponse.SerializeToString,
        ),
        "CreateExtrudedDesignBodyFromFaceProfile": grpc.unary_unary_rpc_method_handler(
            servicer.CreateExtrudedDesignBodyFromFaceProfile,
            request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.CreateExtrudedDesignBodyFromFaceProfileRequest.FromString,
            response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.CreateExtrudedDesignBodyFromFaceProfileResponse.SerializeToString,
        ),
        "DeleteDesignBody": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteDesignBody,
            request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.DeleteDesignBodyRequest.FromString,
            response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.Empty.SerializeToString,
        ),
        "DeleteNamedSelectionByName": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteNamedSelectionByName,
            request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.DeleteNamedSelectionByNameRequest.FromString,
            response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.Empty.SerializeToString,
        ),
        "DeleteComponent": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteComponent,
            request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.DeleteComponentRequest.FromString,
            response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.Empty.SerializeToString,
        ),
        "ProjectCurves": grpc.unary_unary_rpc_method_handler(
            servicer.ProjectCurves,
            request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.ProjectCurvesRequest.FromString,
            response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.ProjectCurvesResponse.SerializeToString,
        ),
        "ImprintCurves": grpc.unary_unary_rpc_method_handler(
            servicer.ImprintCurves,
            request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.ImprintCurvesRequest.FromString,
            response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.ImprintCurvesResponse.SerializeToString,
        ),
        "CreateExtrudedDesignBody": grpc.unary_unary_rpc_method_handler(
            servicer.CreateExtrudedDesignBody,
            request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.CreateExtrudedDesignBodyRequest.FromString,
            response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.CreateExtrudedDesignBodyResponse.SerializeToString,
        ),
        "SetComponentSharedTopology": grpc.unary_unary_rpc_method_handler(
            servicer.SetComponentSharedTopology,
            request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.SetComponentSharedTopologyRequest.FromString,
            response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.Empty.SerializeToString,
        ),
        "CreateCoordinateSystem": grpc.unary_unary_rpc_method_handler(
            servicer.CreateCoordinateSystem,
            request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.CreateCoordinateSystemRequest.FromString,
            response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.CreateCoordinateSystemResponse.SerializeToString,
        ),
        "PowerSelectFacesByAreaRange": grpc.unary_unary_rpc_method_handler(
            servicer.PowerSelectFacesByAreaRange,
            request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.PowerSelectFacesByAreaRangeRequest.FromString,
            response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.PowerSelectFacesByAreaRangeResponse.SerializeToString,
        ),
        "CreatePlanarDesignBody": grpc.unary_unary_rpc_method_handler(
            servicer.CreatePlanarDesignBody,
            request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.CreatePlanarDesignBodyRequest.FromString,
            response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.CreatePlanarDesignBodyResponse.SerializeToString,
        ),
        "New": grpc.unary_unary_rpc_method_handler(
            servicer.New,
            request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.Empty.FromString,
            response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.NewDocumentResponse.SerializeToString,
        ),
        "SaveAs": grpc.unary_unary_rpc_method_handler(
            servicer.SaveAs,
            request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.SaveAsDocumentRequest.FromString,
            response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.SaveAsDocumentResponse.SerializeToString,
        ),
        "CreateComponent": grpc.unary_unary_rpc_method_handler(
            servicer.CreateComponent,
            request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.CreateComponentRequest.FromString,
            response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.CreateComponentResponse.SerializeToString,
        ),
        "CreateBeamCircularProfile": grpc.unary_unary_rpc_method_handler(
            servicer.CreateBeamCircularProfile,
            request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.CreateBeamCircularProfileRequest.FromString,
            response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.CreateBeamCircularProfileResponse.SerializeToString,
        ),
        "CreateBeamBodyLine": grpc.unary_unary_rpc_method_handler(
            servicer.CreateBeamBodyLine,
            request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.CreateBeamBodyLineRequest.FromString,
            response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_board__pb2.CreateBeamBodyLineResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "ansys.api.geometry.v0.Board", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
