# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from ansys.api.geometry import designs_pb2 as ansys_dot_api_dot_geometry_dot_v0_dot_designs__pb2


class DesignsStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
        """Constructor.

        Args:
          channel: A grpc.Channel.
        """
        self.New = channel.unary_unary(
            "/ansys.api.geometry.v0.Designs/New",
            request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_designs__pb2.NewDesignRequest.SerializeToString,
            response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_designs__pb2.Design.FromString,
        )


class DesignsServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def New(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_DesignsServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "New": grpc.unary_unary_rpc_method_handler(
            servicer.New,
            request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_designs__pb2.NewDesignRequest.FromString,
            response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_designs__pb2.Design.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "ansys.api.geometry.v0.Designs", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
