name: Automerge PRs (dependabot and pre-commit)
on: pull_request

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'dependabot/')
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}

      - name: Enable auto-merge for Dependabot PRs
        if: steps.metadata.outputs.update-type != 'version-update:semver-major'
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}

  pre-commit:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'pre-commit-ci-update-config')
    steps:
      - name: Assign PR to pyansys-ci-bot
        run: gh pr edit --add-assignee pyansys-ci-bot "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}

      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}

      - name: Enable auto-merge
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}
