name: Docker images - Push stable
on:
  workflow_dispatch:
    inputs:
      images:
        description: 'Generate image'
        required: true
        default: 'all'
        type: choice
        options:
          - windows-latest
          - linux-latest
          - all

      ansyslab:
        description: 'Push to Ansys Lab'
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: write

jobs:
  windows:
    name: Publish Windows latest image
    runs-on: windows-latest
    if:  inputs.images == 'all' || inputs.images == 'windows-latest'
    env:
      WINDOWS_UNSTABLE: ghcr.io/pyansys/geometry:windows-latest-unstable
      WINDOWS_STABLE_GHCR: ghcr.io/pyansys/geometry:windows-latest
      WINDOWS_STABLE_FUJI: azwepsifujiaksacr.azurecr.io/ansys/discovery/geometry:windows-latest
    steps:
      - name: Login in Github Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Windows latest unstable container
        run: docker pull ${{ env.WINDOWS_UNSTABLE }}

      - name: Tag container as latest (stable) for Github Container registry
        run: docker tag ${{ env.WINDOWS_UNSTABLE }} ${{ env.WINDOWS_STABLE_GHCR }}

      - name: Publish latest stable container in ghcr.io
        run: docker push ${{ env.WINDOWS_STABLE_GHCR }}

      - name: Login in AnsysLab registry
        if: ${{ inputs.ansyslab }}
        uses: docker/login-action@v2
        with:
          registry: azwepsifujiaksacr.azurecr.io
          username: ${{ secrets.FUJI_USER }}
          password: ${{ secrets.FUJI_TOKEN }}

      - name: Tag container as latest (stable) for AnsysLab registry
        if: ${{ inputs.ansyslab }}
        run: docker tag ${{ env.WINDOWS_UNSTABLE }} ${{ env.WINDOWS_STABLE_FUJI }}

      - name: Publish latest stable container in AnsysLab registry
        if: ${{ inputs.ansyslab }}
        run: docker push ${{ env.WINDOWS_STABLE_FUJI }}

  linux:
    name: Publish Linux latest image
    runs-on: ubuntu-latest
    if:  inputs.images == 'all' || inputs.images == 'linux-latest'
    env:
      LINUX_UNSTABLE: ghcr.io/pyansys/geometry:linux-latest-unstable
      LINUX_STABLE_GHCR: ghcr.io/pyansys/geometry:linux-latest
      LINUX_STABLE_FUJI: azwepsifujiaksacr.azurecr.io/ansys/discovery/geometry:linux-latest
    steps:
      - name: Login in Github Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Linux latest unstable container
        run: docker pull ${{ env.LINUX_UNSTABLE }}

      - name: Tag container as latest (stable) for Github Container registry
        run: docker tag ${{ env.LINUX_UNSTABLE }} ${{ env.LINUX_STABLE_GHCR }}

      - name: Publish latest stable container in ghcr.io
        run: docker push ${{ env.LINUX_STABLE_GHCR }}

      - name: Login in AnsysLab registry
        if: ${{ inputs.ansyslab }}
        uses: docker/login-action@v2
        with:
          registry: azwepsifujiaksacr.azurecr.io
          username: ${{ secrets.FUJI_USER }}
          password: ${{ secrets.FUJI_TOKEN }}

      - name: Tag container as latest (stable) for AnsysLab registry
        if: ${{ inputs.ansyslab }}
        run: docker tag ${{ env.LINUX_UNSTABLE }} ${{ env.LINUX_STABLE_FUJI }}

      - name: Publish latest stable container in AnsysLab registry
        if: ${{ inputs.ansyslab }}
        run: docker push ${{ env.LINUX_STABLE_FUJI }}
