name: Docker images - Push stable
on:
  workflow_dispatch:
    inputs:
      images:
        description: 'Generate image'
        required: true
        default: 'all'
        type: choice
        options:
          - windows-latest
          - linux-latest
          - all

      ansyslab:
        description: 'Push to Ansys Lab'
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: write

env:
  WINDOWS_UNSTABLE: ghcr.io/ansys/geometry:windows-latest-unstable
  WINDOWS_STABLE_GHCR: ghcr.io/ansys/geometry:windows-latest
  LINUX_UNSTABLE: ghcr.io/ansys/geometry:linux-latest-unstable
  LINUX_STABLE_GHCR: ghcr.io/ansys/geometry:linux-latest

jobs:
  windows:
    name: Publish Windows latest image
    runs-on: windows-latest
    if:  inputs.images == 'all' || inputs.images == 'windows-latest'
    steps:
      - name: Login in Github Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Windows latest unstable container
        run: docker pull ${{ env.WINDOWS_UNSTABLE }}

      - name: Tag container as latest (stable) for Github Container registry
        run: docker tag ${{ env.WINDOWS_UNSTABLE }} ${{ env.WINDOWS_STABLE_GHCR }}

      - name: Publish latest stable container in ghcr.io
        run: docker push ${{ env.WINDOWS_STABLE_GHCR }}

  windows-ansyslab:
    name: Publish Windows latest image on AnsysLab
    if: inputs.ansyslab
    needs: [windows]
    uses: ./.github/workflows/docker_ansyslab_windows.yml
    secrets: inherit

  linux:
    name: Publish Linux latest image
    runs-on: ubuntu-latest
    if:  inputs.images == 'all' || inputs.images == 'linux-latest'
    steps:
      - name: Login in Github Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Linux latest unstable container
        run: docker pull ${{ env.LINUX_UNSTABLE }}

      - name: Tag container as latest (stable) for Github Container registry
        run: docker tag ${{ env.LINUX_UNSTABLE }} ${{ env.LINUX_STABLE_GHCR }}

      - name: Publish latest stable container in ghcr.io
        run: docker push ${{ env.LINUX_STABLE_GHCR }}

  linux-ansyslab:
    name: Publish Linux latest image on AnsysLab
    if: inputs.ansyslab
    needs: [linux]
    uses: ./.github/workflows/docker_ansyslab_linux.yml
    secrets: inherit
